base_elements:
  - block-device-efi
  - vm
  - cloud-init-datasources
  - dhcp-all-interfaces
base_env_vars:
  DIB_GRUB_TIMEOUT: "0"
  DIB_CLOUD_INIT_DATASOURCES: "ConfigDrive, OpenStack"
  DIB_DHCP_TIMEOUT: "10"
  # DIB_OFFLINE: "1"
  # DIB_AVOID_PACKAGES_UPDATE: "1"
distros:
  - centos:
    extra_elements:
      - centos-minimal
    dib_arch:
      - amd64
      # - arm64
    dib_release:
      - 8-stream
      - 9-stream
  - ubuntu:
    extra_elements:
      - ubuntu
    dib_release:
      - bionic
      - focal
      - jammy
    dib_arch:
      - amd64
      # - arm64
